project:
  type: website
  output-dir: docs
  

website:
  title: "Gabriela's Website"
  navbar:
    left:
        - text: Home
          href: index.qmd
        
        - text: Projects 
          href: about.qmd
       
        - text: Resume
          href: Resume.qmd
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left
    

editor: visual

